### ISSUE TITLE
/etc/varnish/default.vcl grows every time container is reloaded

### ISSUE THREAD

**Issue by chrodriguez** [eea/eea.docker.varnish#11]
In a production system, I've realized the mentioned file grows when service is reloaded. The problem seems to be at https://github.com/eea/eea.docker.varnish/blob/master/varnish/src/assemble_vcls.py#L6 because previous configuration is copied and every time this script runs, it adds a newline at https://github.com/eea/eea.docker.varnish/blob/master/varnish/src/assemble_vcls.py#L13

I'm forking the repo and I'll create a new PR 

Thanks for your great work!

**Comment by avoinea** [comment]
Thank you for your PR!

 Please close if the issue is fixed ;)

**Comment by chrodriguez** [comment]
It seems that it's failing because the download URL of varnish sources has changed. URL https://repo.varnish-cache.org/source/ is not used anymore. I'll make another PR and upgrade a minor patch that fixed a DoS vulnerability

**Comment by chrodriguez** [comment]
I've created another PR fixing the build problem. Please remember to create a new TAG so we're not tied with the latest release

**Comment by avoinea** [comment]
@chrodriguez Thanks! 

**4.1-3.1** released ;)
