### ISSUE TITLE
simple way to include cookie rule missing

### ISSUE THREAD

**Issue by thet** [eea/eea.docker.varnish#19]
Currently there is no easy way to in configure a cookie rule. If cookies are present, the request bypasses the varnish cache completely. A rule snippet which we use for many projects is the following (actually generated by https://github.com/collective/plone.recipe.varnish ):

```
   /* cookies for pass */
    set req.http.UrlNoQs = regsub(req.url, "\?.*$", "");
    if (req.http.Cookie && req.http.Cookie ~ "__ac(|_(name|password|persistent))=") {
        if (req.http.UrlNoQs ~ "\.(js|css|kss|png|gif|jpg|pdf)$") {
            unset req.http.cookie;
            return(pipe);
        }
        return(pass);
    }

    /* Cookie whitelist, remove all not in there */
    if (req.http.Cookie) {
        set req.http.Cookie = ";" + req.http.Cookie;
        set req.http.Cookie = regsuball(req.http.Cookie, "; +", ";");
        set req.http.Cookie = regsuball(req.http.Cookie, ";(statusmessages|cart|__ac|_ZopeId|__cp)=", "; \1=");
        set req.http.Cookie = regsuball(req.http.Cookie, ";[^ ][^;]*", "");
        set req.http.Cookie = regsuball(req.http.Cookie, "^[; ]+|[; ]+$", "");
        if (req.http.Cookie == "") {
            unset req.http.Cookie;
        }
    }

    # Large static files should be piped, so they are delivered directly to the end-user without
    # waiting for Varnish to fully read the file first.
    if (req.url ~ "^[^?]*\.(mp3,mp4|rar|tar|tgz|gz|wav|zip)(\?.*)?$") {
        return(pipe);
    }
```

**Comment by twajr** [comment]
@thet Do you have any particular implementation idea in mind? I'm also looking for something to make cookie specification more generic. Thoughts are appreciated and I'll add to this project if it makes sense to the maintainers.

**Comment by twajr** [comment]
@avoinea The pattern described by @thet above is similar to what we do. Can you comment on this proposal to provide some cookie configuration in the eea image:

A new piece of python, config_cookies.py that is called toward the beginning of docker-entrypoint.sh to extract cookie configuration details from new environment variables similar to how it's done in add_backends.py. It would write the output to conf.d for ultimately inclusion in the final .vcl via the normal iteration.

It would consist of three main areas: cookies for pass, cookie removal, and maybe config for pipe of large files. This is consistent to both our needs an those mentioned by thet. Feedback is appreciated.

**Comment by avoinea** [comment]
@twajr A pull-request would be appreciated as I don't really get it where should this be inserted.

Thank you!

**Comment by twajr** [comment]
@avoinea Okay, I'll do a bit of work first as it sounds like you're open to the possibility. If it doesn't work out, I'll put in our image. This change, though, may allow us to use your image directly. Give me a day or two. Thanks!

**Comment by thet** [comment]
@twajr I'd experiment to remove any cookies for static files. I can't currently think of any use case where file types which are most likely static files would need cookies.
So the first rule would change to (untested):
```
    /* delete cookies for static resources */
    set req.http.UrlNoQs = regsub(req.url, "\?.*$", "");
    if (req.http.UrlNoQs ~ "\.(js|css|kss|gif|png|jpg|mp3|mp4|pdf)$") {
        unset req.http.cookie;
        return(pipe);
    }
```

**Comment by twajr** [comment]
@thet Thanks, yeah, that one looks straight forward. I'm going to focus first on adding setup for 'cookie config' similar to backends. Once that is in place, along with the first item (which is our requirement for a  cookies white list), we can iterate on various cookie options that we expect to configure, like your example.

**Comment by twajr** [comment]
@avoinea I have an initial PR ready, but it's not clear to me how Varnish handles the same vcl_recv sub defined multiple times. It allows me to do it and it compiles, and the default vcl_recv is always placed in the final config as well. So, ultimately with my change there are three defined vcl_recv routines versus two in the current implementation. I'll continue investigating and testing unless you have some words of wisdom around that issue. (Eh, never mind, I can see in the generated C code that all three are called and it must be based on parse order or something). I'll put in a basic PR and we can discuss.

**Comment by avoinea** [comment]
@twajr Thank you! 

`eeacms/varnish:4.1-5.0` released!
