### ISSUE TITLE
Don't force malloc storage backend

### ISSUE THREAD

**Issue by teohhanhui** [eea/eea.docker.varnish#2]
Perhaps `NO_DEFAULT_CACHE=true` or something...

**Comment by avoinea** [comment]
@teohhanhui Can you please detail a little. Which PARAM is doing this?

Thank you!

**Comment by teohhanhui** [comment]
It's hardcoded in `start.sh`:

``` sh
# Size of the cache storage
if [ ! -z "$CACHE_SIZE" ]; then
    PARAMS="$PARAMS -s malloc,$CACHE_SIZE"
else
    PARAMS="$PARAMS -s malloc,128M"
fi
```

**Comment by teohhanhui** [comment]
Let's say I have SSD and want to use file storage instead of memory.

**Comment by avoinea** [comment]
@teohhanhui Ok, I will add a new env $CACHE_STORAGE where you can override default cache like:

```
CACHE_STORAGE=file,/var/lib/varnish/varnish_storage.bin,1G
```

**Comment by teohhanhui** [comment]
Thank you.

**Comment by avoinea** [comment]
Fixed in the latest release. See tags: 
- `:latest`
- `:4s`

Please note that these latest images run varnish on default port `6081` inside container instead of `80`
