### ISSUE TITLE
Statistics / vagent2

### ISSUE THREAD

**Issue by ben-xo** [eea/eea.docker.varnish#6]
Hi there,

How do you suggest getting statistics or logs out of this container? I love the implementation - I have tried several Varnish Dockerfiles, and this one is one of the best. But it's not obvious what would be a sensible way to add vagent2, and vagent2 doesn't seem to have any independent Dockerfiles available.

How would I build vagent2 against the source for this container?
What do you use for monitoring varnish?
Is there anything I should be aware of?

It seems as if a sensible approach might be to fork and add straight to the docker-install.sh ?

**Comment by avoinea** [comment]
> It seems as if a sensible approach might be to fork and add straight to the docker-install.sh ?

Why not, extend it?


```Dockerfile
FROM eeacms/varnish:4.1-1.0

COPY custom-install.sh /tmp/
RUN /tmp/custom-install.sh \
 && rm -rvf /tmp/*
```

**Comment by ben-xo** [comment]
Yeah, that does seem like a good approach as long as the install script doesn't rm the source files.

**Comment by ben-xo** [comment]
@avoinea do you have any answers for the other questions?
